-- Independent Adnan Ai portfolio backend: PostgreSQL, RLS, Storage, and admin settings.
-- Apply only to the selected Supabase project. No Manus data is deleted by this migration.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.portfolio_items (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('website', 'ai_system')),
  title text not null check (char_length(title) between 2 and 180),
  label text not null check (char_length(label) between 2 and 180),
  description text not null check (char_length(description) between 8 and 5000),
  image_url text not null,
  image_alt text not null check (char_length(image_alt) between 4 and 500),
  image_key text,
  public_url text,
  details jsonb not null default '[]'::jsonb,
  trigger text,
  ai_process text,
  output text,
  approval_required boolean not null default false,
  status text not null default 'draft' check (status in ('draft', 'published')),
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id text primary key default 'global' check (id = 'global'),
  hero_image_url text,
  hero_image_key text,
  hero_image_alt text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists portfolio_kind_status_sort_idx
  on public.portfolio_items(kind, status, sort_order, id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists portfolio_items_set_updated_at on public.portfolio_items;
create trigger portfolio_items_set_updated_at
before update on public.portfolio_items
for each row execute procedure public.set_updated_at();

drop trigger if exists site_settings_set_updated_at on public.site_settings;
create trigger site_settings_set_updated_at
before update on public.site_settings
for each row execute procedure public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_portfolio_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and role = 'admin'
  );
$$;

revoke all on function public.is_portfolio_admin() from public;
grant execute on function public.is_portfolio_admin() to authenticated;

alter table public.profiles enable row level security;
alter table public.portfolio_items enable row level security;
alter table public.site_settings enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.portfolio_items from anon, authenticated;
revoke all on table public.site_settings from anon, authenticated;

grant select on table public.profiles to authenticated;
grant select on table public.portfolio_items to anon, authenticated;
grant insert, update, delete on table public.portfolio_items to authenticated;
grant select on table public.site_settings to anon, authenticated;
grant insert, update, delete on table public.site_settings to authenticated;

drop policy if exists "profiles_read_own" on public.profiles;
create policy "profiles_read_own"
on public.profiles for select to authenticated
using (id = (select auth.uid()));

drop policy if exists "portfolio_public_reads_published" on public.portfolio_items;
create policy "portfolio_public_reads_published"
on public.portfolio_items for select to anon, authenticated
using (status = 'published');

drop policy if exists "portfolio_admin_reads_all" on public.portfolio_items;
create policy "portfolio_admin_reads_all"
on public.portfolio_items for select to authenticated
using ((select public.is_portfolio_admin()));

drop policy if exists "portfolio_admin_creates" on public.portfolio_items;
create policy "portfolio_admin_creates"
on public.portfolio_items for insert to authenticated
with check ((select public.is_portfolio_admin()));

drop policy if exists "portfolio_admin_updates" on public.portfolio_items;
create policy "portfolio_admin_updates"
on public.portfolio_items for update to authenticated
using ((select public.is_portfolio_admin()))
with check ((select public.is_portfolio_admin()));

drop policy if exists "portfolio_admin_deletes" on public.portfolio_items;
create policy "portfolio_admin_deletes"
on public.portfolio_items for delete to authenticated
using ((select public.is_portfolio_admin()));

drop policy if exists "settings_public_reads" on public.site_settings;
create policy "settings_public_reads"
on public.site_settings for select to anon, authenticated
using (true);

drop policy if exists "settings_admin_creates" on public.site_settings;
create policy "settings_admin_creates"
on public.site_settings for insert to authenticated
with check ((select public.is_portfolio_admin()));

drop policy if exists "settings_admin_updates" on public.site_settings;
create policy "settings_admin_updates"
on public.site_settings for update to authenticated
using ((select public.is_portfolio_admin()))
with check ((select public.is_portfolio_admin()));

drop policy if exists "settings_admin_deletes" on public.site_settings;
create policy "settings_admin_deletes"
on public.site_settings for delete to authenticated
using ((select public.is_portfolio_admin()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('hero', 'hero', true, 5242880, array['image/jpeg', 'image/png', 'image/webp']),
  ('portfolio', 'portfolio', true, 5242880, array['image/jpeg', 'image/png', 'image/webp']),
  ('workflows', 'workflows', true, 5242880, array['image/jpeg', 'image/png', 'image/webp']),
  ('uploads', 'uploads', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "portfolio_assets_public_read" on storage.objects;
create policy "portfolio_assets_public_read"
on storage.objects for select to anon, authenticated
using (bucket_id in ('hero', 'portfolio', 'workflows', 'uploads'));

drop policy if exists "portfolio_assets_admin_insert" on storage.objects;
create policy "portfolio_assets_admin_insert"
on storage.objects for insert to authenticated
with check (
  bucket_id in ('hero', 'portfolio', 'workflows', 'uploads')
  and (select public.is_portfolio_admin())
);

drop policy if exists "portfolio_assets_admin_update" on storage.objects;
create policy "portfolio_assets_admin_update"
on storage.objects for update to authenticated
using (
  bucket_id in ('hero', 'portfolio', 'workflows', 'uploads')
  and (select public.is_portfolio_admin())
)
with check (
  bucket_id in ('hero', 'portfolio', 'workflows', 'uploads')
  and (select public.is_portfolio_admin())
);

drop policy if exists "portfolio_assets_admin_delete" on storage.objects;
create policy "portfolio_assets_admin_delete"
on storage.objects for delete to authenticated
using (
  bucket_id in ('hero', 'portfolio', 'workflows', 'uploads')
  and (select public.is_portfolio_admin())
);
